name: CI/CD for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Build project
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      env:
        SERVER_USER: vikasms07
        SERVER_HOST: 192.168.0.106
        SERVER_PORT: 22
        SERVER_DIR: /var/www/my-react-app
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p $SERVER_DIR"
        rsync -avz --delete ./dist/ $SERVER_USER@$SERVER_HOST:$SERVER_DIR
        ssh $SERVER_USER@$SERVER_HOST "cd $SERVER_DIR && npm install --production && pm2 restart all"
